### ISSUE TITLE
Полномочия

### ISSUE THREAD

**Issue by elena-mayorova** [antipod237/ipc_practice#5]
У нас практически пустая таблица полномочий. Если открыть самую первую миграцию, то можно увидеть следующее:

```python
connection.execute(
    sa.insert(t_permissions).values([            
        # Admin           
       {'app_name': 'users', 'action': 'all', 'role_id': 1},            
        # TODO: it needs more permissions
            
        # demo            
        {'app_name': 'users', 'action': 'get', 'role_id': 2},            
        # TODO: it needs more permissions        
    ])
)
```

У нас приложения больше, чем одно.
Поэтому хорошо было бы добавить полномочий (прям в первой миграции) и сделать даунгред/апгрейд дб
В принципе действия у всех приложений одинаковы (у админа везде `all`, а у demo веде `get`), так что тут чисто по-копировать по-вставлять и `app_name` поменять.

**Comment by kzagorulko** [comment]
Первично проинициализировать роли и полномочии к ним, согласно ролевой модели 

![model](https://user-images.githubusercontent.com/86552792/168633591-e6970f2a-22dd-4f82-a81c-eaf85aef2b3b.png)
